app:
  name: spring-boot-app
  description: Example Spring Boot Application
  servers:
    0: server1
    1: server2
    2: server3
  environments:
    dev:
      name: Development Environment
      url: https://dev.example.com
    prod:
      name: Prod Environment
      url: https://prod.example.com